
@startuml
participant dApp
participant Wallet
participant RpcEndpoint

note left of Wallet: JSON-RPC
dApp -> Wallet: wallet_RpcEndpointSwitch(RpcEndpoint chainId, rpcUrl, flushPendingTxs)
activate Wallet
note left of RpcEndpoint : JSON-RPC
Wallet -> RpcEndpoint: connectionSwitchRpc(RpcEndpoint chainId, rpcUrl, flushPendingTxs)
activate RpcEndpoint
return JsonRpcResponse, type = Result
return privacyGroupId


@enduml